"""
Django settings for halp project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from halp.settings import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

HOST_URL = os.environ['DJANGO_HOST_URL']
ALLOWED_HOSTS = [HOST_URL, 'localhost']

SECURE_HSTS_SECONDS = 60
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_SSL', 'on')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_PRELOAD = True
# Application definition


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DB_NAME = os.environ['DJANGO_DB_NAME']
DB_USER = os.environ['DJANGO_DB_USER']
DB_PASS = os.environ['DJANGO_DB_PASS']
DB_HOST = os.environ['DJANGO_DB_HOST']
DB_PORT = os.environ['DJANGO_DB_PORT']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_NAME,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}
