# Generated by Django 2.1.3 on 2018-11-29 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halp_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reqeust_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
