# Generated by Django 2.1.3 on 2018-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halp_backend', '0002_auto_20181129_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
